### PR TITLE
Added german language

### PR DESCRIPTION
**Pull request by lgund**
Just as it says. Added the german translation.

### CODE REVIEW

**Comment by ArgoZhang** [comment]
thanks for you contribution

**Comment by ArgoZhang** [comment]
@lgund hi, can you give me a star if you like

**Comment by lgund** [comment]
I already did. If it's okey I will translate the Dokumentation site also to German.

**Comment by ArgoZhang** [comment]
@lgund Wow! sound good! This will be a very heavy workload

**Pull request merged**
