### PR TITLE
Should support IDynamicObject in IEditorItem CanWrite 

### PR DESCRIPTION
**Pull request by tiansfather**
# {PR title}

Summary of the changes (Less than 80 chars)

比如DynamicColumnObject不继承DynamicObject，只是实现了IDynamicObject接口，故在方法中需要调整判断方式

## Description

fixes #{bug number} (in this specific format)

## Regression?

- [ ] Yes
- [ ] No

[If yes, specify the version the behavior has regressed from]

[是否影响老版本]

## Risk

- [ ] High
- [ ] Medium
- [ ] Low

[Justify the selection above]

## Verification

- [ ] Manual (required)
- [ ] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [ ] N/A

## ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Merge the latest code from the main branch

## Summary by Sourcery

Bug Fixes:
- Fix issue where DynamicColumnObject did not inherit DynamicObject but implemented the IDynamicObject interface.

### CODE REVIEW

**Comment by ArgoZhang** [comment]
@tiansfather 感谢大佬提交 PR， 请补充 Issue 写明示例，我需要了解代码运行逻辑，方便以后维护

**Comment by tiansfather** [comment]
本来是希望DynamicColumnObject动态对象可以不需要EditTemplate直接通过设置ComponentType支持单表维护,如下代码
`@page "/"
@attribute [TabItemOption(Text = "Index", Closable = false)]

<Table TItem="DynamicColumnsObject" Items="CustomDynamicItems"
       IsStriped="true" IsBordered="true" ShowToolbar="true" ShowColumnList="true" ShowAddButton="true" ShowDefaultButtons="true" ShowRefresh="false">
    <TableColumns>
        @foreach (var element in StaticColumnList)
        {
            <TableColumn Field="@element" FieldName="@element" Text="@element" Sortable="true" Filterable="true" >
                <Template Context="v">
                    <div>Template - @v.Value</div>
                </Template>
                @*必须设置EditTemplate才能进行单表维护*@
                <EditTemplate Context="v">
                    <div class="col-md-12">
                        <BootstrapInput Value="@v.GetValue(element)" DisplayText="@element"></BootstrapInput>
                    </div>
                </EditTemplate>
            </TableColumn>
        }
    </TableColumns>
</Table>
@code{
    [NotNull]
    private IEnumerable<DynamicColumnsObject>? CustomDynamicItems { get; set; }
    private static List<string> StaticColumnList =>    [        "A",    "B",    "C",    "Z"    ];

    /// <summary>
    /// OnInitialized
    /// </summary>
    protected override void OnInitialized()
    {
        base.OnInitialized();
        // 构造动态列
        CustomDynamicItems = Enumerable.Range(1, 10).Select(index => new DynamicColumnsObject( StaticColumnList.ToDictionary(d => d, d => (object?)$"{d}{index}")));
    }

}
`

不过就算按上面的修改了，后面调用Utility.CreateComponentByFieldType还是会有问题，除非在这个方法里也判断model是不是IDynamicObject
image

最简单的就是设置EditTemplate就ok了，大佬有什么建议吗

**Comment by ArgoZhang** [comment]
@tiansfather 动态类型根据实现不同。这里是很难实现 `ValueChagned` 回调的。所以你看源码应该能看到很多地方都是排除了动态类型。包括缓存哪里都时不支持的

**Comment by tiansfather** [comment]
恩，那没事，这个pr先撤回

**Pull request closed without merging**
