### PR TITLE
Add a portuguese-Brazilian translation locale

### PR DESCRIPTION
**Pull request by ricardopdv**
Add a pt.json file with Brazil language translation

### CODE REVIEW

**Comment by densen2014** [comment]
muy buenos trabajos, muchas gracias!

**Comment by densen2014** [comment]
estoy en madrid ,😀

**Comment by ArgoZhang** [comment]
@ricardopdv thanks

**Comment by ricardopdv** [comment]
I will try to collaborate more. It’s a great component !

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Argo ***@***.***>
Enviado:quarta-feira, 17 de novembro de 2021 22:27
Para: ***@***.***>
Cc:Ricardo ***@***.***>; ***@***.***>
Assunto: Re: [dotnetcore/BootstrapBlazor] Add a portuguese-Brazilian translation locale (PR #138)


@ricardopdv<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fricardopdv&data=04%7C01%7C%7Ce850a4ffe8ee4aa167e208d9aa329695%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637727956521787317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RnOketY6Xac0G9ts%2FowSlBWfHpBaIAPdTVTkXa4CQuM%3D&reserved=0> thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnetcore%2FBootstrapBlazor%2Fpull%2F138%23issuecomment-972406750&data=04%7C01%7C%7Ce850a4ffe8ee4aa167e208d9aa329695%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637727956521787317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SN7vzdp6dk84dVvo%2FoyP3%2B%2BqmtqtCQuIswJsDNypoDA%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADMNKHLOFJOKKEPG7YA4Z5DUMRJADANCNFSM5IH4K5OQ&data=04%7C01%7C%7Ce850a4ffe8ee4aa167e208d9aa329695%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637727956521797316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JiloNiv22xmqqR%2BwMD8EIzwEf0EoI3K0qbvVCkmjw2Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ce850a4ffe8ee4aa167e208d9aa329695%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637727956521797316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v%2FllKxw0NUyIP2Cjg4w1rSlR%2B1Fc%2BITwcSWlkycoFYM%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ce850a4ffe8ee4aa167e208d9aa329695%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637727956521807307%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w1TynERTRpV6fqy1SYLdWJLiXhNLDglAgqJbwuKaAYc%3D&reserved=0>.

**Comment by ArgoZhang** [comment]
@ricardopdv great! may I invent you as a member? you can push the branch into repro.

**Pull request merged**
